services:
  - type: web
    name: user-management-frontend
    env: node
    buildCommand: npm ci && npm run build
    startCommand: serve -s build -p $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.17.0